spring:
  profiles:
    include: [common]
  datasource:
    url: jdbc:mysql://121.196.46.197:3306/novel_biz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ww564654
    driver-class-name: com.mysql.cj.jdbc.Driver


pic:
  save:
    type: 2  #图片保存方式, 1不保存，使用网络图片 ，2本地保存
    path: /var/pic  #图片保存路径



